const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../assets/course-data.js'),P=require('../assets/progress.js');
test('blank progress has no artificial achievements',()=>{const p=P.empty();assert.deepEqual(p.completed,[]);assert.deepEqual(p.labs,{});assert.deepEqual(p.quizzes,{});});
test('valid notes round-trip without executing markup',()=>{const p=P.empty();p.labs['u1-l1']={note:'<script>example, not executable</script>',done:true};assert.deepEqual(P.validate(p,C),p);});
test('imports reject unknown units, labs and scores',()=>{for(const change of [p=>p.completed=[7],p=>p.labs['invented']={note:'x',done:true},p=>p.quizzes['1']={best:7,last:3,attempts:1},p=>p.labs['u1-l1']={note:'',done:true},p=>p.version=2,p=>p.labs['u1-l1']={note:'x'.repeat(3001),done:false}]){const p=P.empty();change(p);assert.throws(()=>P.validate(p,C));}});
test('malformed nested values never erase a valid state',()=>{for(const value of [null,[],{version:1},'text',{...P.empty(),completed:null},{...P.empty(),quizzes:{'1':null}},{...P.empty(),labs:JSON.parse('{"__proto__":{"done":true,"note":"x"}}')}])assert.throws(()=>P.validate(value,C));});
test('quiz scoring checks every supplied choice',()=>{const u=C.units[0];assert.equal(P.score(u.quiz,u.quiz.map(q=>q.answer)),6);assert.equal(P.score(u.quiz,u.quiz.map(q=>(q.answer+1)%q.options.length)),0);assert.throws(()=>P.score(u.quiz,[]));assert.throws(()=>P.score(u.quiz,Array(6).fill(9)));});
test('best score never falls and attempts increment once per result',()=>{let p=P.empty();p=P.recordQuiz(p,1,5,6);p=P.recordQuiz(p,1,2,6);assert.deepEqual(p.quizzes['1'],{best:5,last:2,attempts:2});assert.equal(P.empty().quizzes['1'],undefined);});
test('timer uses a deadline and does not spend time while paused',()=>{let t=P.timer(60);t=P.start(t,1000);assert.equal(P.remaining(t,21000),40);t=P.pause(t,21500);assert.equal(P.remaining(t,100000),39.5);t=P.start(t,100000);assert.equal(P.remaining(t,110000),29.5);assert.equal(P.remaining(t,200000),0);});
