/* npm install --no-save playwright && npx playwright install chromium */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..'),course=require('../assets/course-data.js'),D=require('../assets/learning-data.js');
const base='http://localhost:18765/',service='http://localhost:18787',key='browser-test-key-not-a-deployment-secret',children=[];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function ready(url){for(let i=0;i<50;i++){try{if((await fetch(url)).ok)return;}catch{}await sleep(100);}throw Error('Test server not ready: '+url);}
(async()=>{
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'uclm-browser-'));let browser;
 try{
 children.push(spawn('python3',['-m','http.server','18765'],{cwd:root,stdio:'ignore'}));
 children.push(spawn('python3',['server/app.py'],{cwd:root,stdio:'inherit',env:{...process.env,CLASSROOM_HOST:'127.0.0.1',CLASSROOM_PORT:'18787',CLASSROOM_ORIGINS:'http://localhost:18765',CLASSROOM_TEACHER_KEY:key,CLASSROOM_DB:path.join(tmp,'class.db')}}));
 await ready(base);await ready(service+'/api/health');
 browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),...(process.env.CHROMIUM_ARGS?{args:JSON.parse(process.env.CHROMIUM_ARGS).filter(a=>!['--disable-web-security','--allow-running-insecure-content'].includes(a))}:{})});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(12000);
 if(process.env.PYODIDE_CACHE)await page.route('https://cdn.jsdelivr.net/pyodide/v314.0.7/full/**',async route=>{const name=new URL(route.request().url()).pathname.split('/').pop(),file=path.join(process.env.PYODIDE_CACHE,name);if(!fs.existsSync(file))throw Error('Missing pinned runtime cache: '+name);await route.fulfill({status:200,headers:{'Access-Control-Allow-Origin':'*','Content-Type':name.endsWith('.mjs')?'text/javascript':name.endsWith('.wasm')?'application/wasm':'application/octet-stream'},body:fs.readFileSync(file)});});
 const go=async route=>{await page.goto(base+'#'+route);await page.locator('h1').waitFor();};fs.mkdirSync(root+'/.artifacts',{recursive:true});
 for(const route of ['home','challenges/1','practice','code/3','study/4/12','study/1/3.5','search','glossary','schedule','review','compare','live']){await go(route);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route);}
 console.log('Routes loaded without overflow.');
 for(const l of course.labs){await go('lab/'+l.id);const frame=page.frameLocator('#lecture-frame');await frame.locator('#slide-'+l.slide+'.current').waitFor();await page.waitForFunction(()=>document.querySelector('#lecture-frame').contentDocument.body.classList.contains('study'));assert.ok(await frame.locator('#slide-'+l.slide+' button,#slide-'+l.slide+' input,#slide-'+l.slide+' select').count()>0,l.id);}
 await go('lab/u1-l1');const note='<script>not executed</script> · prediction → evidence';await page.locator('#evidence').fill(note);await page.locator('#lab-done').check();await go('home');await go('lab/u1-l1');assert.equal(await page.locator('#evidence').inputValue(),note);assert.equal(await page.locator('#lab-done').isChecked(),true);await page.screenshot({path:root+'/.artifacts/v2-lab.png',fullPage:true});
 for(let i=1;i<=6;i++){await go('challenges/'+i);assert.equal(await page.locator('[data-challenge]').count(),3);for(const c of D.challenges.filter(x=>x.unit===i)){await page.locator(`[data-challenge="${c.id}"]`).fill('Evidence for '+c.id);await page.locator(`[data-challenge-done="${c.id}"]`).check();}}
 await page.reload();assert.equal(await page.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem('uclm-si-progress-v1')).learning.challenges).length),18);
 const download=page.waitForEvent('download');await page.locator('[data-learn=report]').click();assert.equal((await download).suggestedFilename(),'intelligent-systems-evidence.md');
 await go('search');await page.locator('#global-search').fill('reopening');assert.ok(await page.locator('#global-results a[href^="#study/"]').count()>0);await page.locator('#global-results a[href^="#study/"]').first().click();await page.locator('#study-slide').waitFor();assert.match(page.url(),/#study\/\d+\/\d+/);
 await go('compare');await page.locator('[data-scenario=cost]').click();await page.locator('[data-learn=compare-run]').click();const costs=await page.locator('#compare-results tbody tr').allTextContents();assert.match(costs[0],/SOLVED10/);assert.match(costs[1],/SOLVED3/);await page.locator('#comparison-input').fill('{invalid after the run');const jsonDownload=page.waitForEvent('download');await page.locator('[data-learn=compare-download]').click();const data=JSON.parse(fs.readFileSync(await (await jsonDownload).path(),'utf8'));assert.deepEqual(data.settings.instance,require('../assets/comparisons.js').scenarios.cost);
 console.log('28 integrated labs, autosave, 18 challenges, search and comparison export passed.');
 await go('code/1');await page.locator('#python-code').fill('print(1 + 2)');await page.reload();assert.equal(await page.locator('#python-code').inputValue(),'print(1 + 2)');
 const execute=async()=>{await page.locator('[data-learn=check]').click();await page.waitForFunction(()=>document.querySelector('#stop-python').disabled,null,{timeout:80000});};
 for(let i=1;i<=6;i++){await go('code/'+i);await page.locator('#python-code').fill(D.exercises[i-1].worked);await execute();const output=await page.locator('#python-output').textContent();assert.match(output,/PASS/,'Python unit '+i+': '+output);console.log('Actual browser Python checks passed for unit '+i);}
 await page.screenshot({path:root+'/.artifacts/v2-python.png',fullPage:true});
 await page.locator('#python-code').fill('this is invalid python !');await execute();assert.match(await page.locator('#python-output').textContent(),/SyntaxError/);
 await page.locator('#python-code').fill('while True: pass');await page.locator('[data-learn=run]').click();await page.waitForFunction(()=>document.querySelector('#runner-status').textContent.includes('running'),null,{timeout:70000});await page.locator('[data-learn=stop]').click();assert.match(await page.locator('#runner-status').textContent(),/stopped/);
 await page.locator('#python-code').fill('print("RECOVERED")');await page.locator('[data-learn=run]').click();await page.waitForFunction(()=>document.querySelector('#stop-python').disabled,null,{timeout:80000});assert.match(await page.locator('#python-output').textContent(),/RECOVERED/);
 await page.locator('#python-code').fill('while True: pass');await page.locator('[data-learn=run]').click();await page.waitForFunction(()=>document.querySelector('#stop-python').disabled,null,{timeout:80000});assert.match(await page.locator('#python-output').textContent(),/10 seconds/);
 console.log('Syntax errors, Stop, recovery and automatic timeout passed.');
 await go('live');await page.locator('#live-url').fill(service);await page.locator('#teacher-connect input').fill(key);await page.locator('#teacher-connect button').click();await page.locator('#create-room input').fill('Browser teaching trial');await page.locator('#create-room button').click();await page.locator('#invite-code').waitFor();const code=await page.locator('#invite-code').textContent();
 const student=await browser.newPage({viewport:{width:390,height:844}});student.on('pageerror',e=>errors.push(e.message));await student.goto(base+'#live');await student.locator('#live-url').fill(service);await student.locator('#join-room [name=code]').fill(code);await student.locator('#join-room [name=alias]').fill('Learner A');await student.locator('#join-room button').click();await student.locator('#submission-preview').waitFor();
 await page.locator('#create-poll [name=question]').fill('Which algorithm uses path cost?');await page.locator('#create-poll [name=options]').fill('BFS\nUCS');await page.locator('#create-poll button').click();await student.locator('[name=live-vote][value="1"]').check({timeout:18000});await student.locator('#vote-form button').click();await student.waitForFunction(()=>document.querySelector('#live-status').textContent.includes('Answer recorded'));
 await page.locator('#close-poll').click();await page.waitForFunction(()=>document.querySelector('#poll-panel').textContent.includes('UCS: 1')&&document.querySelector('#poll-panel').textContent.includes('Closed'));
 await student.locator('#submission-preview').fill('My prediction and evidence.');await student.locator('#submit-evidence button.primary').click();await student.waitForFunction(()=>document.querySelector('#live-status').textContent.includes('Receipt:'));
 await page.locator('.feedback-form textarea').fill('Explain one assumption.',{timeout:18000});await page.locator('.feedback-form button').click();await student.waitForFunction(()=>document.querySelector('#student-receipts').textContent.includes('Explain one assumption.'),null,{timeout:18000});
 await student.reload();await student.locator('#resume-session').click();await student.locator('#student-receipts').getByText('Explain one assumption.').waitFor();
 assert.equal(await page.evaluate(k=>JSON.stringify(localStorage).includes(k)||JSON.stringify(sessionStorage).includes(k),key),false);
 const exported=page.waitForEvent('download');await page.locator('#export-records').click();assert.equal((await exported).suggestedFilename(),'classroom-submissions.csv');await page.locator('#load-solutions').click();await page.locator('#private-solutions').getByText('No protected solution files have been configured on the server.').waitFor();
 await page.screenshot({path:root+'/.artifacts/v2-teacher.png',fullPage:true});await student.screenshot({path:root+'/.artifacts/v2-student-mobile.png',fullPage:true});
 for(const route of ['challenges/1','code/1','study/3/20','search','glossary','schedule','review','compare','live','lab/u6-l5']){await student.goto(base+'#'+route);await student.locator('h1').waitFor();assert.equal(await student.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'mobile '+route);}
 const restricted=await browser.newPage();await restricted.addInitScript(()=>{Storage.prototype.setItem=function(){throw Error('quota test')};});await restricted.goto(base+'#lab/u1-l1');await restricted.locator('#evidence').fill('Unsaved locally but retained in memory.');assert.match(await restricted.locator('#autosave-status').textContent(),/Storage unavailable/);
 assert.deepEqual(errors,[]);console.log('PASS: real teacher/student polls, receipts, feedback, resume, secrets kept out of storage and mobile routes.');
 }finally{if(browser)await browser.close();for(const child of children)child.kill();fs.rmSync(tmp,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1});
