#!/usr/bin/env python3
"""Build static learning content, browser exercise contracts and slide search index."""
from pathlib import Path
import ast,json,re,subprocess
from html.parser import HTMLParser
ROOT=Path(__file__).resolve().parents[1]
class Plain(HTMLParser):
    def __init__(self): super().__init__();self.parts=[]
    def handle_data(self,x): self.parts.append(x)
def plain(x):
    p=Plain();p.feed(x);return re.sub(r'\s+',' ',' '.join(p.parts)).strip()
def write(name,data):
    (ROOT/f'assets/{name}.js').write_text('/* Generated by scripts/build_learning_data.py */\nconst '+name.upper().replace('-','_')+' = '+json.dumps(data,ensure_ascii=False,indent=2)+';\nif(typeof module!=="undefined")module.exports='+name.upper().replace('-','_')+';\n')
course=json.loads(subprocess.check_output(['node','-e',"process.stdout.write(JSON.stringify(require('./assets/course-data.js')))"],cwd=ROOT))
index=[]
for u in course['units']:
    for i,s in enumerate(json.loads((ROOT/f"authoring/unit{u['id']}-content.json").read_text()),1):
        index.append(dict(unit=u['id'],slide=i,title=plain(s['title']),text=plain(s['body']),notes=s['notes']))
write('search-data',index)
# Concepts are linked to the existing questions in their exact order.
concepts=[
['Rationality','PEAS and sensors','Partial observability','Stochastic transitions','Coupled actions','Performance measures'],
['Problem formulation','Breadth-first search','Uniform-cost search','Goal testing','Depth limits','Duplicate states'],
['Admissibility','Consistency','Greedy search','A* reopening','Heuristic bounds','Optimality conditions'],
['Variables and domains','Constraint propagation','Arc consistency','MRV','Global constraints','Local search'],
['Minimax assumptions','Alpha–beta bounds','Move ordering','Evaluation functions','Expectimax','Utility scale'],
['Return and discounting','Bellman backups','Q-learning targets','SARSA targets','Exploration','Termination and evaluation']]
# Match labels to the actual question wording below rather than trusting a fixed syllabus order.
concept_by_question={
 1:['Rationality','PEAS: sensors','Partial observability','Stochastic transitions','Coupled actions','Performance measures'],
 2:['BFS optimality','UCS priorities','Depth-limited cutoff','Search-tree growth','State formulation','Resource cutoffs'],
 3:['A* priorities','Admissibility','Consistency','A* reopening','Loopover lower bounds','Greedy search limits'],
 4:['CSP formulation','MRV','Least-constraining value','Arc-consistency limits','Global satisfiability','Min-conflicts cutoffs'],
 5:['Minimax backup','Pruning correctness','Terminal utility','Cutoff bounds and ties','Expected utility','Decision thresholds'],
 6:['Discounted return','Q-learning target','SARSA target','True termination','External truncation','Epsilon-greedy policy']}

for u in course['units']:
 for i,q in enumerate(u['quiz']): q['concept']=concept_by_question.get(u['id'],concepts[u['id']-1])[i]
works=[
 dict(title='When memory changes the action',explanation='In room A with dirt, SUCK has priority. After both rooms have been checked clean, STOP is rational only under the static-dirt assumption. A room label alone cannot encode what happened in the other room.',trace=['(A, dirty, {}) → SUCK','(A, clean, {A}) → RIGHT','(B, clean, {A,B}) → STOP'],limitation='If dirt can reappear, the stopping rule must change; define when old information expires.'),
 dict(title='The first goal generated need not be cheapest',explanation='Use S→G cost 10, S→A cost 1 and A→G cost 2. UCS removes S at g=0, A at g=1, then G at g=3. The expensive G entry becomes obsolete. Testing the goal when it is generated would return cost 10.',trace=['Frontier after S: A(1), G(10)','After A: G(3), G(10)','Remove G(3): solution S→A→G, cost 3'],limitation='BFS optimises edge count when edge costs are uniform; UCS requires nonnegative costs.'),
 dict(title='Why a state may need reopening',explanation='Use S→A:3, S→B:1, B→A:1, A→G:2, B→G:100 with h(S)=4, h(A)=0, h(B)=3, h(G)=0. A is first expanded at g=3. B later discovers A at g=2; reopen it to obtain the optimum.',trace=['Expand A at g=3; discover G at g=5','Expand B; improve A to g=2','Reopen A; improve G to g=4'],limitation='Admissibility does not imply consistency. Rejecting all previously expanded states can lose optimality.'),
 dict(title='Local support is not a global solution',explanation='A triangle with two colours is arc-consistent: each colour at one endpoint has an opposite colour at its neighbour. Yet the three pairwise disequalities cannot all be satisfied. Search or stronger reasoning is still needed.',trace=['A=red forces B=blue and C=blue','B≠C is violated','Trying A=blue yields the symmetric contradiction'],limitation='Forward checking is weaker than enforcing full arc consistency; neither alone proves every network satisfiable.'),
 dict(title='Pruning preserves the decision',explanation='At a MAX root with MIN children [5,6] and [2,9], the left child evaluates to 5. In the right child, the first value 2 is already below alpha=5, so its second leaf cannot improve the root choice.',trace=['Left MIN: min(5,6)=5; alpha becomes 5','Right MIN sees 2; beta becomes 2','beta≤alpha: prune 9; root value stays 5'],limitation='The returned cutoff value for the right child is a bound; it is not necessarily its exact value on a different tree.'),
 dict(title='The target determines the update',explanation='For Q=0.5, reward −0.04, next values [4,1,−2,0], alpha=0.2 and gamma=0.9, Q-learning uses target 3.56 and returns 1.112. SARSA selecting action 1 uses target 0.86 and returns 0.572.',trace=['Q-learning: 0.5 + 0.2 × (−0.04 + 0.9×4 − 0.5) = 1.112','SARSA: 0.5 + 0.2 × (−0.04 + 0.9×1 − 0.5) = 0.572','True termination removes continuation; an external time limit does not.'],limitation='Training return includes exploration. Evaluate a frozen greedy policy separately and repeat across seeds.')]
briefs=[
 [('Specify the agent','Create a PEAS description for a campus delivery robot. Identify one hidden state and one stochastic outcome.','A PEAS table, two environment assumptions and a justified agent architecture.'),('Repair the vacuum policy','Implement the two-room policy. Trace a dirty room, an unvisited clean room and the stopping condition.','A three-case trace, passing checks and an explanation of the memory state.'),('Break the assumptions','Construct a dirt-reappearing environment where stopping fails. Propose a memory expiry or inspection policy.','A reproducible failure trace, revised performance measure and policy comparison.')],
 [('Trace the frontier','Trace BFS and UCS on S→G:10, S→A:1, A→G:2. State when the goal is tested.','Frontier contents at each removal and both path costs.'),('Implement a reliable baseline','Complete UCS with best-g tracking, stale-entry removal and an expansion limit. Test start=goal and unreachable goals.','Code, an edge case and distinct SOLVED/EXHAUSTED/CUTOFF outcomes.'),('Measure search growth','Create five shared instances of increasing depth. Compare BFS and UCS with identical budgets.','Published instances, expansion counts, costs and an account of all cutoff runs.')],
 [('Audit a heuristic','For the reopening example, compute h*(S), h*(A), h*(B), h*(G). Check every consistency inequality.','A true-distance table and the exact edge that violates consistency.'),('Implement reopening','Complete A* and reproduce the cost-4 solution after improving an already expanded A.','Frontier trace, path replay and an explanation of the stale-entry check.'),('Design and defend a bound','Derive a Loopover lower bound. Compare it with ceil(misplaced/7) on shallow instances certified by BFS.','An admissibility argument, counterexample search and controlled measurements.')],
 [('Separate local and global reasoning','Show why a two-colour triangle is arc-consistent yet unsatisfiable.','Support for each value on each arc and a global contradiction.'),('Solve and explain','Implement MRV with forward checking for graph colouring. Compare a triangle with two and three colours.','Complete assignment or failure proof by search, plus domains after each decision.'),('Compare propagation','Add AC-3 and compare its domain deletions and search decisions against forward checking.','Identical networks, explicit effort metrics and one case where propagation pays off.')],
 [('Trace exact values and bounds','Annotate minimax and alpha–beta on [[5,6],[2,9]]. Identify what can be pruned.','Root decision, leaf count and exact-versus-bound labels.'),('Implement stable decisions','Complete minimax with optional pruning and leftmost tie handling. Compare both modes on multiple trees.','Matching root values and actions, with a trace for a tied bound.'),('Investigate move ordering','Reorder the same game tree without changing utilities and compare leaf evaluations.','Original and reordered trees, preserved root value and explained differences.')],
 [('Calculate targets','Compute Q-learning and SARSA updates for the worked example and a true terminal transition.','Numerical calculations and a clear bootstrap decision for each case.'),('Separate learning and evaluation','Use the comparison tool to train Q-learning and SARSA under the same seeds and budgets.','Mean and standard deviation of frozen-policy returns, success rate and cutoffs.'),('Investigate reward and generalisation','Change reward design or exploration and evaluate on held-out starts with at least five seeds.','Hypothesis, fixed protocol, dispersion and a discussion of reward exploitation or leakage.')]
]
hints=[['Separate observations from hidden state.','State the performance measure before choosing an action.'],['A generated goal is only a candidate.','Compare cumulative cost, not depth, for UCS.'],['Track the best g for each state.','An admissible bound can still be inconsistent.'],['Write down domains after every assignment.','A supported pair is not a complete assignment.'],['Alpha belongs to MAX; beta belongs to MIN.','Keep the first action unless a later value is strictly better.'],['Write the target before applying alpha.','Freeze learning and exploration during greedy evaluation.']]
rubric=[dict(item='Model and assumptions',weight=25,description='Define the instance, objective and conditions under which the claim holds.'),dict(item='Correctness and reasoning',weight=35,description='Use a replayable trace, derivation or verified implementation.'),dict(item='Experimental evidence',weight=25,description='Publish settings and a controlled comparison, including failed cases.'),dict(item='Explanation and limits',weight=15,description='Connect observations to the model and state a limitation.')]
ref=(ROOT/'practice/python/reference.py').read_text();tree=ast.parse(ref);segments={n.name:ast.get_source_segment(ref,n) for n in tree.body if isinstance(n,(ast.FunctionDef,ast.ClassDef))}
student=(ROOT/'practice/python/student.py').read_text();st={n.name:ast.get_source_segment(student,n) for n in ast.parse(student).body if isinstance(n,ast.FunctionDef)}
functions=['vacuum_action','uniform_cost_search','a_star','solve_coloring','minimax','td_update']
deps=[[],['SearchResult','_search'],['SearchResult','_search'],[],['GameResult'],[]]
checks=[
"assert vacuum_action('A', True, {'A','B'}) == 'SUCK'\nassert vacuum_action('A', False, {'A'}) == 'RIGHT'\nassert vacuum_action('B', False, {'A','B'}) == 'STOP'",
"g={'S':[('G',10),('A',1)],'A':[('G',2)]}\nr=uniform_cost_search(g,'S','G')\nassert r.cost==3 and r.path==['S','A','G']\nassert uniform_cost_search(g,'S','G',0).status=='CUTOFF'\nassert uniform_cost_search(g,'G','S').status=='EXHAUSTED'",
"g={'S':[('A',3),('B',1)],'A':[('G',2)],'B':[('A',1),('G',100)]}\nr=a_star(g,'S','G',{'S':4,'A':0,'B':3,'G':0})\nassert r.cost==4 and r.path==['S','B','A','G']",
"g={'A':{'B','C'},'B':{'A','C'},'C':{'A','B'}}\nr=solve_coloring(g,['red','green','blue'])\nassert r and all(r[a]!=r[b] for a,ns in g.items() for b in ns)\nassert solve_coloring(g,['red','blue']) is None\nassert solve_coloring({},[])=={}",
"a=minimax([[5,6],[2,9]],True); b=minimax([[5,6],[2,9]],False)\nassert a.value==b.value==5 and a.action==b.action==0\nassert a.leaves==3 and b.leaves==4\nassert minimax([[5,6],[5,0]]).action==0",
"a=(.5,-.04,[4,1,-2,0],.2,.9)\nassert abs(td_update(*a)-1.112)<1e-9\nassert abs(td_update(*a,method='sarsa',next_action=1)-.572)<1e-9\nassert abs(td_update(.5,1,[],.2,.9,terminated=True)-.6)<1e-9\nassert abs(td_update(*a,truncated=True)-1.112)<1e-9"]
# Preserve dataclass decorators (ast.get_source_segment excludes decorators).
for name in ['SearchResult','GameResult']:segments[name]='@dataclass\n'+segments[name]
prefix='from dataclasses import dataclass\nfrom heapq import heappush, heappop\nfrom itertools import count\nfrom math import inf, isfinite\n\n'
exercises=[]
for i,name in enumerate(functions):
    shared='\n\n'.join(segments[d] for d in deps[i] if d in ['SearchResult','GameResult'])
    exercises.append(dict(unit=i+1,function=name,starter=prefix+shared+'\n\n'+st[name]+'\n',worked=prefix+'\n\n'.join(segments[d] for d in deps[i]+[name])+'\n',checks=checks[i]+"\nprint('PASS: public exercise checks. Add your own edge case.')",hints=hints[i]))
glossary_text='''Agent|Agente|A system that selects actions from observations or internal state.|1
Actuator|Actuador|A mechanism through which an agent changes its environment.|1
Percept|Percepción|An observation available to the agent at a particular time.|1
Rationality|Racionalidad|Choosing actions that maximise expected performance given available information.|1
PEAS|Rendimiento, entorno, actuadores y sensores|A framework for specifying an agent task.|1
Partial observability|Observabilidad parcial|The observation does not reveal all decision-relevant state.|1
State space|Espacio de estados|The states and transitions admitted by a problem model.|2
Frontier|Frontera|Discovered search nodes waiting to be expanded.|2
Path cost|Coste del camino|The sum of action costs along a path.|2
Completeness|Completitud|A guarantee of finding a solution when one exists under stated assumptions.|2
Optimality|Optimalidad|A guarantee of returning a solution with minimum cost under stated assumptions.|2
Cutoff|Interrupción por límite|A search stopped by a resource limit; not proof of unsolvability.|2
Heuristic|Heurística|An estimate used to guide a search decision.|3
Admissibility|Admisibilidad|A heuristic never overestimates the optimal remaining cost.|3
Consistency|Consistencia|For every edge, h(n) is at most its cost plus h(n′).|3
Reopening|Reapertura|Expanding a state again after discovering a better path to it.|3
Dominance|Dominancia|One admissible heuristic is at least as large as another at every state.|3
Tie-breaking|Desempate|A specified rule for choosing among equal-priority candidates.|3
Domain|Dominio|The current candidate values for a CSP variable.|4
Constraint|Restricción|A condition that valid assignments must satisfy.|4
Arc consistency|Consistencia de arco|Every remaining value has support in the neighbouring variable on that arc.|4
Forward checking|Comprobación hacia delante|Removing incompatible values from unassigned neighbours after an assignment.|4
MRV|Mínimos valores restantes|Choose an unassigned variable with the smallest current domain.|4
Global constraint|Restricción global|A constraint involving a collection of variables, such as AllDifferent.|4
Minimax|Minimax|Choose against an optimal opponent in a zero-sum decision model.|5
Alpha–beta pruning|Poda alfa–beta|Skip branches that cannot change the minimax root decision.|5
Evaluation function|Función de evaluación|An estimate of position quality at a search cutoff.|5
Expectimax|Expectimax|Back up expected utility at chance nodes and choices at decision nodes.|5
Utility|Utilidad|The numerical preference measure used by the decision model.|5
Move ordering|Ordenación de movimientos|The order in which successor actions are considered.|5
MDP|Proceso de decisión de Markov|A model of states, actions, transitions, rewards and an objective.|6
Return|Retorno|The accumulated, possibly discounted, future reward.|6
Discount factor|Factor de descuento|The weight gamma applied per future time step.|6
Bellman backup|Actualización de Bellman|A value update using immediate reward and successor values.|6
Temporal difference|Diferencia temporal|Learning from a sampled reward and a bootstrapped value estimate.|6
Q-learning|Q-learning|An off-policy update that uses the largest next-action value.|6
SARSA|SARSA|An on-policy update using the next action actually selected.|6
Exploration|Exploración|Taking actions to obtain information rather than only exploiting current estimates.|6
Termination|Terminación|The task reaches a genuine terminal state.|6
Truncation|Truncamiento|An external limit stops interaction without necessarily terminating the underlying task.|6'''
glossary=[dict(en=a,es=b,definition=c,unit=int(d)) for a,b,c,d in (line.split('|') for line in glossary_text.splitlines())]
weeks=[(1,'Agents: task and environment',1,'Specify PEAS and environment assumptions.','Compare reflex and model-based behaviour.','Vacuum laboratory and foundation challenge.'),(2,'Agents: modelling and evidence',1,'Rationality and expected utility.','Coupled Loopover actions and invariant reasoning.','Agent policy exercise and applied challenge.'),(3,'Search: formalise and trace',2,'States, actions, goals and path costs.','BFS, DFS and duplicate detection.','Trace shared instances and report frontier contents.'),(4,'Search: costs and limits',2,'UCS and goal-test timing.','Depth limits, cutoffs and resource growth.','Implement UCS; replay returned paths.'),(5,'Heuristics: justify the estimate',3,'Greedy search and A*.','Admissibility, consistency and counterexamples.','Heuristic audit and foundation challenge.'),(6,'Heuristics: implement and compare',3,'Reopening and stale entries.','Loopover lower bounds and experimental design.','Implement A*; compare with a certified shallow baseline.'),(7,'Constraints: model and propagate',4,'Variables, domains and constraints.','Forward checking and arc consistency.','Colouring laboratory and local-versus-global reasoning.'),(8,'Constraints: search efficiently',4,'MRV and value ordering.','Global constraints and local search.','Implement colouring; compare propagation strategies.'),(9,'Games: reason against an opponent',5,'Minimax assumptions and utility.','Alpha–beta exact values and bounds.','Trace pruning and implement stable tie handling.'),(10,'Games: evaluate and order',5,'Cutoff evaluation and move ordering.','Chance nodes and expectimax.','Compare leaf evaluations on the same tree.'),(11,'RL: model sequential rewards',6,'MDPs, returns and discounting.','Bellman backups and value iteration.','Calculate targets and inspect value propagation.'),(12,'RL: learn from samples',6,'TD, Q-learning and SARSA.','Exploration and terminal versus truncated episodes.','Run the Python exercise and multi-seed comparisons.'),(13,'RL: evaluate and diagnose',6,'Frozen-policy evaluation and dispersion.','Reward design and generalisation.','Complete the applied/extension RL challenge.'),(14,'Project clinic',3,'Audit Loopover models and optimality claims.','Reproduce another team’s experiment.','Peer review with the project rubric.'),(15,'Synthesis and defence',6,'Connect assumptions across the six models.','Explain a failure case and defend a design choice.','Project demonstration, targeted review and reflection.')]
challenges=[dict(id=f'u{i+1}-{level}',unit=i+1,level=level,title=t,prompt=p,evidence=e,minutes=[20,45,75][j],hints=hints[i],rubric=rubric) for i,unit in enumerate(briefs) for j,(level,(t,p,e)) in enumerate(zip(['foundation','applied','extension'],unit))]
write('learning-data',dict(examples=works,exercises=exercises,challenges=challenges,glossary=glossary,weeks=[dict(week=w,title=t,unit=u,before=f'Review the learning outcomes for unit {u}; write one question.',theory1=a,theory2=b,lab=c,after='Save an evidence report, add one edge case and revisit one uncertain concept.') for w,t,u,a,b,c in weeks],concepts={q['id']:dict(label=q['concept'],unit=u['id']) for u in course['units'] for q in u['quiz']}))
print(f'Built {len(index)} slide records, {len(challenges)} challenges, {len(glossary)} glossary terms and {len(weeks)} weeks.')
