'use strict';
const slides=[...document.querySelectorAll('.slide')];
let current=Math.max(0,Math.min(slides.length-1,parseInt(location.hash.slice(1),10)-1||0));
const byId=id=>document.getElementById(id);
const indexDialog=byId('index-dialog');
let notesOpen=false;
function fit(){const el=byId('stage');if(document.body.classList.contains('study'))return;document.documentElement.style.setProperty('--scale',Math.min((el.clientWidth-24)/1440,(el.clientHeight-24)/810));}
function updateNotes(){const s=slides[current];byId('notes-title').textContent=(current+1)+'. '+s.querySelector('h1,h2').textContent;byId('notes-text').textContent=s.dataset.notes;}
function go(i,scroll=true){current=Math.max(0,Math.min(slides.length-1,i));slides.forEach((s,j)=>{s.classList.toggle('current',j===current);s.setAttribute('aria-hidden',document.body.classList.contains('study')?'false':String(j!==current));});byId('counter').textContent=(current+1)+' / '+slides.length;byId('prev').disabled=current===0;byId('next').disabled=current===slides.length-1;try{history.replaceState(null,'','#'+(current+1));}catch(e){}updateNotes();if(document.body.classList.contains('study')&&scroll)slides[current].scrollIntoView({block:'start'});}
function toggleNotes(){if(document.body.classList.contains('study')){const detail=slides[current].querySelector('details');detail.open=!detail.open;detail.scrollIntoView({block:'center'});return;}notesOpen=!notesOpen;byId('notes-panel').hidden=!notesOpen;byId('notes').setAttribute('aria-expanded',String(notesOpen));fit();}
function toggleStudy(){document.body.classList.toggle('study');const on=document.body.classList.contains('study');byId('study').textContent=on?'Presentation':'Study mode';byId('study').setAttribute('aria-pressed',String(on));go(current,on);fit();}
byId('prev').onclick=()=>go(current-1);byId('next').onclick=()=>go(current+1);byId('notes').onclick=toggleNotes;byId('close-notes').onclick=toggleNotes;byId('study').onclick=toggleStudy;byId('index').onclick=()=>indexDialog.showModal();byId('close-index').onclick=()=>indexDialog.close();
byId('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){byId('status').textContent='Full screen is not available in this view. Open the downloaded file in a browser tab.';}};
byId('print').onclick=()=>{if(document.body.classList.contains('study'))toggleStudy();window.print();};
slides.forEach((s,i)=>{const b=document.createElement('button');b.innerHTML='<span>'+String(i+1).padStart(2,'0')+'</span>'+s.querySelector('h1,h2').textContent;b.onclick=()=>{indexDialog.close();go(i);};byId('index-items').appendChild(b);});
document.addEventListener('keydown',e=>{if(indexDialog.open)return;if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.ctrlKey||e.metaKey||e.altKey)return;const key=e.key.toLowerCase();if(key===' '&&['BUTTON','A','SUMMARY'].includes(document.activeElement.tagName))return;if(['arrowright','pagedown',' '].includes(key)){e.preventDefault();go(current+1);}if(['arrowleft','pageup'].includes(key)){e.preventDefault();go(current-1);}if(key==='home'){e.preventDefault();go(0);}if(key==='end'){e.preventDefault();go(slides.length-1);}if(key==='i')indexDialog.showModal();if(key==='n')toggleNotes();if(key==='e')toggleStudy();if(key==='f')byId('fullscreen').click();});
window.addEventListener('resize',fit);window.addEventListener('hashchange',()=>go(parseInt(location.hash.slice(1),10)-1||0));
document.querySelectorAll('.reveal').forEach(b=>{b.addEventListener('click',()=>{const a=b.nextElementSibling;a.hidden=!a.hidden;b.setAttribute('aria-expanded',String(!a.hidden));b.textContent=a.hidden?'Show explanation':'Hide explanation';});});
