const clone=x=>JSON.parse(JSON.stringify(x));
const fmt=x=>x===Infinity?'∞':x===-Infinity?'−∞':Number.isInteger(x)?String(x):Number(x.toFixed(3)).toString();
function makeTree(groups){return {id:'R',role:'MAX',children:groups.map(([id,values])=>({id,role:'MIN',children:values.map((u,i)=>({id:id+(i+1),u}))}))};}
const PRESETS={source:[['A',[3,12]],['B',[8,2]]],prune:[['A',[5,6]],['B',[2,9]]],tie:[['A',[5,6]],['B',[5,0]]]};
const ORDER_GROUPS=[['A',[4,11,7]],['B',[1,8,9]],['C',[6,3,10]]];
function treeExact(n){return 'u' in n?n.u:(n.role==='MAX'?Math.max:Math.min)(...n.children.map(treeExact));}
function leavesOf(n){return 'u' in n?[n.id]:n.children.flatMap(leavesOf);}
function nodesOf(n){return [n.id,...(n.children||[]).flatMap(nodesOf)];}
function searchTree(root,pruning=true){const state={values:{},visited:[],pruned:[],active:'R',leaves:0,nodes:0},events=[];
 const emit=(message,a,b)=>events.push({...clone(state),message,alpha:fmt(a),beta:fmt(b)});
 function visit(n,alpha,beta){const originalA=alpha,originalB=beta;state.active=n.id;state.visited.push(n.id);state.nodes++;emit(`Enter ${n.id}${n.role?' ('+n.role+')':''}.`,alpha,beta);
  if('u' in n){state.leaves++;state.values[n.id]={v:n.u,type:'exact'};emit(`Evaluate ${n.id}: ${n.u}.`,alpha,beta);return {v:n.u,type:'exact',action:null};}
  const max=n.role==='MAX';let v=max?-Infinity:Infinity,action=null,allExact=true,skipped=false;
  for(let i=0;i<n.children.length;i++){const c=n.children[i],r=visit(c,alpha,beta);allExact=allExact&&r.type==='exact';if(action===null||(max?r.v>v:r.v<v)){v=r.v;action=c.id;}state.active=n.id;state.values[n.id]={v,type:max?'lower':'upper'};
   if(pruning){if(max)alpha=Math.max(alpha,v);else beta=Math.min(beta,v);}
   emit(`${n.id} keeps ${max?'maximum':'minimum'} ${fmt(v)} after ${c.id}.`,alpha,beta);
   if(pruning&&alpha>=beta&&i<n.children.length-1){const omitted=n.children.slice(i+1);state.pruned.push(...omitted.flatMap(nodesOf));skipped=true;emit(`Cutoff at ${n.id}: α ≥ β. Skip ${omitted.map(c=>c.id).join(', ')}.`,alpha,beta);break;}
  }
  const type=allExact&&!skipped?'exact':v<=originalA?'upper':v>=originalB?'lower':'exact';state.values[n.id]={v,type};state.active=n.id;emit(`Return ${n.id}: ${type==='upper'?'≤':type==='lower'?'≥':''}${fmt(v)}${n.id==='R'?'; choose '+action:''}.`,alpha,beta);return {v,type,action};
 }
 const result=visit(root,-Infinity,Infinity);return {root,result,events,leaves:state.leaves,nodes:state.nodes,skipped:state.pruned.filter(id=>leavesOf(root).includes(id)).length};}
function treeSvg(root,event){let leafCount=leavesOf(root).length,cursor=0;const W=leafCount*125+100,pos={};function layout(n,depth){let x;if('u' in n){x=112.5+cursor*125;cursor++;}else{n.children.forEach(c=>layout(c,depth+1));x=n.children.reduce((s,c)=>s+pos[c.id].x,0)/n.children.length;}pos[n.id]={x,y:depth===0?55:depth===1?190:335};}layout(root,0);
 let svg=`<svg class="game-tree live-tree" viewBox="0 0 ${W} 405" role="img" aria-label="Game tree. ${event.message.replace(/"/g,'')}">`;
 function drawEdges(n){for(const c of n.children||[]){const a=pos[n.id],b=pos[c.id];svg+=`<line class="${event.pruned.includes(c.id)?'pruned-edge':''}" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"/>`;drawEdges(c);}}drawEdges(root);
 function draw(n){const {x,y}=pos[n.id],r=event.values[n.id],val=r?(r.type==='lower'?'≥':r.type==='upper'?'≤':'')+fmt(r.v):'?',pruned=event.pruned.includes(n.id);svg+=`<g class="${n.role==='MAX'?'max':n.role==='MIN'?'min':'terminal'} ${pruned?'pruned-node':''} ${event.active===n.id?'active-node':''} ${r?'evaluated-node':''}"><rect x="${x-46}" y="${y-35}" width="92" height="70" rx="5"/><text class="inside-role" x="${x}" y="${y-10}">${n.id}${n.role?' · '+n.role:''}</text><text x="${x}" y="${y+21}">${val}</text></g>`;(n.children||[]).forEach(draw);}draw(root);return svg+'</svg>';}
function metrics(trace,e){return `<div><span>Leaves read</span><b>${e.leaves}/${leavesOf(trace.root).length}</b></div><div><span>Window</span><b>[${e.alpha}, ${e.beta}]</b></div>`;}
let trace,tracePos=0;
function drawTrace(){const e=trace.events[tracePos];byId('trace-tree').innerHTML=treeSvg(trace.root,e);byId('trace-event').textContent=e.message;byId('trace-metrics').innerHTML=metrics(trace,e);byId('trace-result').textContent=tracePos===trace.events.length-1?`Root value ${trace.result.v} · Action ${trace.result.action} · ${trace.skipped} skipped ${trace.skipped===1?'leaf':'leaves'}.`:`Event ${tracePos+1}/${trace.events.length}`;byId('trace-back').disabled=tracePos===0;byId('trace-step').disabled=byId('trace-run').disabled=tracePos===trace.events.length-1;}
function resetTrace(){trace=searchTree(makeTree(PRESETS[byId('trace-case').value]),byId('trace-method').value==='ab');tracePos=0;drawTrace();}
byId('trace-case').onchange=byId('trace-method').onchange=resetTrace;byId('trace-reset').onclick=resetTrace;byId('trace-step').onclick=()=>{tracePos=Math.min(trace.events.length-1,tracePos+1);drawTrace();};byId('trace-back').onclick=()=>{tracePos=Math.max(0,tracePos-1);drawTrace();};byId('trace-run').onclick=()=>{tracePos=trace.events.length-1;drawTrace();};resetTrace();
function orderTree(mode){const root=makeTree(ORDER_GROUPS);if(mode!=='natural'){const good=mode==='good';root.children.sort((a,b)=>good?treeExact(b)-treeExact(a):treeExact(a)-treeExact(b));root.children.forEach(n=>n.children.sort((a,b)=>good?a.u-b.u:b.u-a.u));}return root;}
let order,orderPos=0;
function drawOrder(){const e=order.events[orderPos];byId('order-tree').innerHTML=treeSvg(order.root,e);byId('order-event').textContent=e.message;byId('order-metrics').innerHTML=metrics(order,e);byId('order-back').disabled=orderPos===0;byId('order-step').disabled=byId('order-run').disabled=orderPos===order.events.length-1;}
function resetOrder(){order=searchTree(orderTree(byId('order-mode').value),true);orderPos=0;drawOrder();}byId('order-mode').onchange=byId('order-reset').onclick=resetOrder;byId('order-step').onclick=()=>{orderPos=Math.min(order.events.length-1,orderPos+1);drawOrder();};byId('order-back').onclick=()=>{orderPos=Math.max(0,orderPos-1);drawOrder();};byId('order-run').onclick=()=>{orderPos=order.events.length-1;drawOrder();};resetOrder();
const LINES=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
function terminal(board){for(const [a,b,c] of LINES)if(board[a]!=='.'&&board[a]===board[b]&&board[a]===board[c])return {value:board[a]==='X'?100:-100,winner:board[a],line:[a,b,c]};return board.includes('.')?null:{value:0,winner:'draw',line:[]};}
function player(board){return [...board].filter(x=>x==='X').length===[...board].filter(x=>x==='O').length?'X':'O';}
function moves(board){if(terminal(board))return [];return [...board].flatMap((c,i)=>c==='.'?[{square:i,board:board.slice(0,i)+player(board)+board.slice(i+1)}]:[]);}
const valueCache=new Map();
function exactValue(board){if(valueCache.has(board))return valueCache.get(board);const t=terminal(board);if(t){valueCache.set(board,t.value);return t.value;}const v=(player(board)==='X'?Math.max:Math.min)(...moves(board).map(m=>exactValue(m.board)));valueCache.set(board,v);return v;}
function exactAction(board){const ms=moves(board);if(!ms.length)return null;const target=exactValue(board);return ms.find(m=>exactValue(m.board)===target).square;}
function features(board){const f={openX:0,openO:0,threatX:0,threatO:0,center:board[4]==='X'?1:board[4]==='O'?-1:0};for(const line of LINES){const x=line.filter(i=>board[i]==='X').length,o=line.filter(i=>board[i]==='O').length,empty=3-x-o;if(!o)f.openX++;if(!x)f.openO++;if(x===2&&empty===1)f.threatX++;if(o===2&&empty===1)f.threatO++;}return f;}
function evaluate(board,wo=3,wt=10){const f=features(board);return Math.max(-90,Math.min(90,wo*(f.openX-f.openO)+wt*(f.threatX-f.threatO)+2*f.center));}
function cutoffValue(board,depth,wo=3,wt=10){const t=terminal(board);if(t)return t.value;if(depth===0)return evaluate(board,wo,wt);return (player(board)==='X'?Math.max:Math.min)(...moves(board).map(m=>cutoffValue(m.board,depth-1,wo,wt)));}
function cutoffDecision(board,depth,wo=3,wt=10){const t=terminal(board);if(t)return {terminal:t,action:null,score:t.value,scores:[]};const scores=moves(board).map(m=>({square:m.square,score:cutoffValue(m.board,depth-1,wo,wt),exact:exactValue(m.board)})),score=(player(board)==='X'?Math.max:Math.min)(...scores.map(x=>x.score));return {terminal:null,action:scores.find(s=>s.score===score).square,score,scores};}
const EVAL_BOARDS={horizon:'......O.X',tactic:'XX.OO....',terminal:'XO..X.O.X'};let evalState;
function staticBoard(board,highlight=null){const t=terminal(board);return '<div class="ttt-static">'+[...board].map((c,i)=>`<span class="${t&&t.line.includes(i)?'win-cell ':''}${highlight===i?'suggested ':''}${c==='.'?'empty':'mark-'+c}">${c==='.'?i+1:c}</span>`).join('')+'</div>';}
function drawEval(){const b=EVAL_BOARDS[byId('eval-position').value],d=Number(byId('eval-depth').value),wo=Number(byId('eval-open').value),wt=Number(byId('eval-threat').value),r=cutoffDecision(b,d,wo,wt),f=features(b);evalState={board:b,depth:d,wo,wt,...r,rootExact:exactValue(b)};byId('depth-label').textContent=d;byId('open-label').textContent=wo;byId('threat-label').textContent=wt;byId('eval-board').innerHTML=staticBoard(b,r.action);byId('eval-features').textContent=`Current features: open X/O ${f.openX}/${f.openO}; threats X/O ${f.threatX}/${f.threatO}; centre ${f.center}.`;
 byId('eval-scores').innerHTML=r.terminal?'<p>Terminal position: no further move.</p>':'<table><thead><tr><th>Square</th><th>Search score</th><th>Exact move value</th></tr></thead><tbody>'+r.scores.map(s=>`<tr class="${s.square===r.action?'chosen-row':''}"><td>${s.square+1}${s.square===r.action?' ← chosen':''}</td><td>${s.score}</td><td>${s.exact}</td></tr>`).join('')+'</tbody></table>';
 byId('eval-status').textContent=r.terminal?`Exact terminal utility: ${r.score}. Depth and feature weights cannot change this outcome.`:`Choose square ${r.action+1}. Search score ${r.score}; exact value after this move ${r.scores.find(s=>s.square===r.action).exact}.`;}
['eval-position','eval-depth','eval-open','eval-threat'].forEach(id=>byId(id).addEventListener('input',drawEval));function resetEval(){byId('eval-position').value='horizon';byId('eval-depth').value=1;byId('eval-open').value=3;byId('eval-threat').value=10;drawEval();}byId('eval-reset').onclick=resetEval;drawEval();
let playBoard='.........',playHistory=[],playLog='No moves yet.';
function playDraw(){const t=terminal(playBoard);byId('play-board').innerHTML=[...playBoard].map((c,i)=>`<button class="${c==='.'?'empty':'mark-'+c} ${t&&t.line.includes(i)?'win-cell':''}" data-square="${i}" ${c!=='.'||t?'disabled':''} aria-label="Square ${i+1}${c==='.'?', empty':', '+c}">${c==='.'?i+1:c}</button>`).join('');byId('play-value').textContent=exactValue(playBoard);byId('play-log').textContent=playLog;byId('play-status').textContent=t?(t.winner==='draw'?'Draw. Neither player completed a line.':t.winner+' wins. The game has ended.'):'Your turn: X. O will minimize X’s exact outcome.';byId('play-best').disabled=!!t;byId('play-undo').disabled=!playHistory.length;}
function playX(i){if(terminal(playBoard)||playBoard[i]!=='.'||player(playBoard)!=='X')return;playHistory.push({board:playBoard,log:playLog});playBoard=playBoard.slice(0,i)+'X'+playBoard.slice(i+1);playLog='X: '+(i+1);if(!terminal(playBoard)){const j=exactAction(playBoard);playBoard=playBoard.slice(0,j)+'O'+playBoard.slice(j+1);playLog+=' · O: '+(j+1);}playDraw();}
byId('play-board').onclick=e=>{const b=e.target.closest('button[data-square]');if(b)playX(Number(b.dataset.square));};byId('play-new').onclick=()=>{playBoard='.........';playHistory=[];playLog='No moves yet.';playDraw();};byId('play-best').onclick=()=>{const i=exactAction(playBoard);if(i!==null)playX(i);};byId('play-undo').onclick=()=>{const old=playHistory.pop();if(old){playBoard=old.board;playLog=old.log;playDraw();}};playDraw();
function probabilityDecision(p){const risk=16*p-6;return {p,risk,safe:4,choice:Math.abs(risk-4)<1e-9?'Tie':risk>4?'Risk':'Safe'};}
function drawChance(){const r=probabilityDecision(Number(byId('chance-p').value));byId('chance-p-label').textContent=fmt(r.p);byId('chance-value').textContent=fmt(r.risk);byId('chance-choice').textContent=r.choice==='Tie'?'Tie · display policy keeps Safe':r.choice;byId('chance-status').textContent=r.choice==='Risk'&&r.p===1?'At p=1, Risk returns 10 with certainty.':r.choice==='Risk'?'Higher expected utility. An individual risky play can still return −6.':r.choice==='Tie'?'Both actions have expected utility 4, with different outcome distributions.':'Safe has the larger expected utility at this probability.';}
byId('chance-p').oninput=drawChance;for(const [id,p] of [['chance-half',0.5],['chance-tie',0.625],['chance-high',0.75]])byId(id).onclick=()=>{byId('chance-p').value=p;drawChance();};drawChance();
window.presentation={go,slides,makeTree,searchTree,treeExact,orderTree,terminal,player,moves,exactValue,exactAction,features,evaluate,cutoffValue,cutoffDecision,probabilityDecision,getTrace:()=>({trace:clone(trace),position:tracePos}),getOrder:()=>({trace:clone(order),position:orderPos}),getEval:()=>clone(evalState),getPlay:()=>({board:playBoard,history:clone(playHistory),terminal:terminal(playBoard)}),reset:()=>{byId('trace-case').value='source';byId('trace-method').value='minimax';resetTrace();byId('order-mode').value='natural';resetOrder();resetEval();byId('play-new').click();byId('chance-p').value=0.5;drawChance();}};
window.addEventListener('beforeprint',()=>slides.forEach(s=>s.setAttribute('aria-hidden','false')));window.addEventListener('afterprint',()=>go(current,false));
