// Vacuum agent: access is limited to location, local dirt and its own memory.
let vac={};
function resetVac(){vac={pos:0,dirty:[true,true],mem:[null,null],steps:0,last:'Not executed',log:[]};renderVac();}
function renderVac(){byId('vac-world').innerHTML=[0,1].map(i=>'<div class="'+(vac.pos===i?'occupied':'')+'"><small>Square '+(i?'B':'A')+'</small><b>'+(vac.pos===i?'Robot':'No robot')+'</b><span>'+(vac.dirty[i]?'Dirty':'Clean')+'</span></div>').join('');byId('vac-percept').textContent=(vac.pos?'B':'A')+' · '+(vac.dirty[vac.pos]?'dirty':'clean');const memory=byId('vac-policy').value==='memory';byId('vac-memory').textContent=memory?vac.mem.map((x,i)=>(i?'B':'A')+': '+(x===null?'unknown':x?'dirty':'clean')).join(' · '):'No memory retained';byId('vac-action').textContent=vac.last+' · '+vac.steps+' steps';byId('vac-log').textContent=vac.log.slice(-4).join(' / ');}
function vacStep(){const memory=byId('vac-policy').value==='memory';const localDirty=vac.dirty[vac.pos];if(memory)vac.mem[vac.pos]=localDirty;let action;if(localDirty){action='Suck';vac.dirty[vac.pos]=false;if(memory)vac.mem[vac.pos]=false;}else if(memory&&vac.mem.every(x=>x===false)){action='Wait';}else{action=vac.pos===0?'Right':'Left';vac.pos=1-vac.pos;}vac.steps++;vac.last=action;vac.log.push(vac.steps+': '+action);renderVac();}
byId('vac-step').onclick=vacStep;byId('vac-reset').onclick=resetVac;byId('vac-policy').onchange=resetVac;resetVac();
function updateEU(){const p=Number(byId('prob').value)/100,eu=18*p-8;byId('prob-value').textContent=Math.round(p*100)+'%';byId('fast-eu').textContent=eu.toFixed(1);byId('fast-bar').style.width=(100*(eu+8)/18)+'%';byId('eu-choice').textContent=eu>6?'Higher expected utility: fast route.':eu<6?'Higher expected utility: safe route.':'Both routes have equal expected utility.';}
byId('prob').oninput=updateEU;updateEU();
const scenarios={plain:['The entire board is visible and action effects are known.',[['Observation','Full'],['Transition','Deterministic and known'],['Design requirement','Search over the available state.']]],hidden:['Some tiles are hidden from the agent.',[['Observation','Partial'],['Transition','Still deterministic and known'],['Design requirement','Maintain possibilities about hidden tiles.']]],noise:['An action may fail with a known probability.',[['Observation','Full after each action'],['Transition','Stochastic and known'],['Design requirement','Consider contingencies and verify the outcome.']]],unknown:['The board is visible, but the agent does not know the movement rules.',[['Observation','Full'],['Transition','Deterministic but unknown to the agent'],['Design requirement','Learn the effects of actions.']]]};
function setScenario(k){const [s,r]=scenarios[k];byId('scenario-setup').textContent=s;byId('scenario-result').innerHTML='<div class="rows">'+r.map(([a,b])=>'<div><strong>'+a+'</strong><span>'+b+'</span></div>').join('')+'</div>';document.querySelectorAll('.scenario').forEach(b=>{b.classList.toggle('active',b.dataset.case===k);b.setAttribute('aria-pressed',String(b.dataset.case===k));});}
document.querySelectorAll('.scenario').forEach(b=>b.onclick=()=>setScenario(b.dataset.case));setScenario('plain');
let board=[],phase=0,moveCount=0,pending=null,highlight=[];
function rowMove(state,r,d){const out=state.slice();for(let c=0;c<4;c++)out[r*4+(c+d+4)%4]=state[r*4+c];return out;}
function colMove(state,c,d){const out=state.slice();for(let r=0;r<4;r++)out[((r+d+4)%4)*4+c]=state[r*4+c];return out;}
function applyAction(state,r,c,d){return colMove(rowMove(state,r,d),c,d);}
function renderLoop(){byId('loop-board').innerHTML=board.map((x,i)=>'<span class="'+(highlight.includes(i)?'moved':'')+'">'+String(x).padStart(2,'0')+'</span>').join('');byId('loop-state').textContent=board.map(x=>String(x).padStart(2,'0')).join('');byId('loop-count').textContent=moveCount;byId('loop-step').textContent=phase?'2 · Move column':'1 · Move row';['loop-row','loop-col','loop-dir'].forEach(id=>byId(id).disabled=!!phase);}
function resetLoop(){board=Array.from({length:16},(_,i)=>i);phase=0;moveCount=0;pending=null;highlight=[];byId('loop-explain').textContent='Ordered goal. Action 02+ starts with row 0.';byId('loop-row').value='0';byId('loop-col').value='2';byId('loop-dir').value='1';renderLoop();}
function stepLoop(){if(phase===0){pending={r:+byId('loop-row').value,c:+byId('loop-col').value,d:+byId('loop-dir').value};board=rowMove(board,pending.r,pending.d);highlight=[0,1,2,3].map(c=>pending.r*4+c);phase=1;byId('loop-explain').textContent='Phase 1: row '+pending.r+' shifts '+(pending.d===1?'right':'left')+'. Column '+pending.c+' still needs to move.';}else{board=colMove(board,pending.c,pending.d);highlight=[0,1,2,3].map(r=>r*4+pending.c);phase=0;moveCount++;byId('loop-explain').textContent='Action '+pending.r+pending.c+(pending.d===1?'+':'−')+' complete. Column '+pending.c+' moves '+(pending.d===1?'down':'up')+'. '+(board.every((x,i)=>x===i)?'The goal is satisfied.':'This is a successor state.');}renderLoop();}
byId('loop-step').onclick=stepLoop;byId('loop-reset').onclick=resetLoop;byId('loop-mix').onclick=()=>{resetLoop();[[0,2,1],[1,3,-1],[3,1,1]].forEach(([r,c,d])=>board=applyAction(board,r,c,d));moveCount=3;byId('loop-explain').textContent='Reproducible mix: 02+, 13− and 31+. Explore further actions.';renderLoop();};resetLoop();
window.presentation={go,slides,vacStep,resetVac,getVac:()=>JSON.parse(JSON.stringify(vac)),rowMove,colMove,applyAction,resetLoop,stepLoop,getLoop:()=>({board:[...board],phase,moveCount}),setScenario};
