const AU=['WA','NT','Q','SA','NSW','V','T'], COLORS=['R','G','B'];
const AUEDGES=[['WA','NT'],['WA','SA'],['NT','SA'],['NT','Q'],['SA','Q'],['SA','NSW'],['SA','V'],['Q','NSW'],['NSW','V']];
const clone=x=>JSON.parse(JSON.stringify(x));
const auProblem={vars:AU,edges:AUEDGES,test:(a,x,b,y)=>x!==y};
function neighbors(P,x){return P.edges.flatMap(([a,b])=>a===x?[b]:b===x?[a]:[]);}
function initialDomains(vars,values){return Object.fromEntries(vars.map(v=>[v,[...values]]));}
function enumerate(P,D){const out=[],A={};function visit(i){if(i===P.vars.length){out.push({...A});return;}const x=P.vars[i];for(const v of D[x]){if(neighbors(P,x).every(y=>!(y in A)||P.test(x,v,y,A[y]))){A[x]=v;visit(i+1);delete A[x];}}}visit(0);return out;}
function ac3(P,input){const D=clone(input),q=P.edges.flatMap(([a,b])=>[[a,b],[b,a]]),events=[];let revisions=0;
 const snap=(message,removed=[])=>events.push({D:clone(D),queue:clone(q),message,removed,revisions});
 snap('All directed arcs enter the queue.');
 if(P.vars.some(x=>!D[x].length)){snap('An initial domain is empty: FAILURE.');return {D,ok:false,events,revisions};}
 while(q.length){const [x,y]=q.shift();revisions++;const removed=D[x].filter(v=>!D[y].some(w=>P.test(x,v,y,w)));D[x]=D[x].filter(v=>!removed.includes(v));
  if(removed.length){if(!D[x].length){snap(`REVISE ${x} → ${y}: remove ${removed.join(', ')}. Empty domain: FAILURE.`,removed);return {D,ok:false,events,revisions};}
   for(const z of neighbors(P,x)){if(z!==y&&!q.some(([a,b])=>a===z&&b===x))q.push([z,x]);}}
  snap(`REVISE ${x} → ${y}: ${removed.length?'remove '+removed.join(', ')+' from '+x:'no deletion'}.`,removed);
 }
 events[events.length-1].message+=' Queue empty: ARC_CONSISTENT.';return {D,ok:true,events,revisions};}
function renderDomains(id,vars,D,A={}){byId(id).innerHTML=vars.map(v=>`<div class="domain-row${!D[v].length?' empty':''}"><b>${v}</b><span>${D[v].length?'{'+D[v].join(', ')+'}':'∅'}</span><small>${v in A?'assigned':'candidate'+(D[v].length===1?'':'s')}</small></div>`).join('');}
let mapA={};
function mapDraw(){const D=Object.fromEntries(AU.map(x=>[x,x in mapA?[mapA[x]]:COLORS.filter(v=>neighbors(auProblem,x).every(y=>!(y in mapA)||mapA[y]!==v))]));renderDomains('map-domains',AU,D,mapA);const bad=AUEDGES.filter(([a,b])=>a in mapA&&b in mapA&&mapA[a]===mapA[b]);
 document.querySelectorAll('#map-graph [data-csp-node]').forEach(g=>{const x=g.dataset.cspNode;g.setAttribute('class','color-'+(mapA[x]||''));g.querySelector('.node-value').textContent=mapA[x]||'—';});
 document.querySelectorAll('#map-graph [data-csp-edge]').forEach(e=>{const [a,b]=e.dataset.cspEdge.split('-');e.classList.toggle('violated',bad.some(([x,y])=>x===a&&y===b));});
 const empties=AU.filter(x=>!D[x].length);byId('map-status').textContent=bad.length?`${bad.length} assigned-edge conflict${bad.length===1?'':'s'}: ${bad.map(e=>e.join('–')).join(', ')}.`:empties.length?'Empty domain: '+empties.join(', ')+'. This branch fails.':Object.keys(mapA).length===7?'SOLUTION: all nine edges pass.':'No assigned-edge conflict. A valid completion is not guaranteed.';
 return {A:clone(mapA),D,bad};}
byId('map-set').onclick=()=>{const x=byId('map-var').value,v=byId('map-value').value;if(v)mapA[x]=v;else delete mapA[x];mapDraw();};byId('map-clear').onclick=()=>{mapA={};mapDraw();};byId('map-example').onclick=()=>{mapA={WA:'R',Q:'G'};mapDraw();};mapDraw();
function backtrackTrace(config){const P=auProblem,events=[],counts={attempts:0,backtracks:0},base=initialDomains(AU,COLORS.slice(0,config.colors));let solution=null;
 const emit=(message,D,A,status='SEARCHING')=>events.push({message,D:clone(D),A:clone(A),counts:{...counts},status});
 function legal(x,D,A){return D[x].filter(v=>neighbors(P,x).every(y=>!(y in A)||P.test(x,v,y,A[y])));}
 function visit(D,A){if(Object.keys(A).length===AU.length){solution={...A};emit('SOLUTION: complete assignment; all constraints pass.',D,A,'SOLUTION');return true;}
  let vars=AU.filter(x=>!(x in A));if(config.order==='mrv')vars.sort((x,y)=>legal(x,D,A).length-legal(y,D,A).length||neighbors(P,y).filter(z=>!(z in A)).length-neighbors(P,x).filter(z=>!(z in A)).length||AU.indexOf(x)-AU.indexOf(y));
  const x=vars[0];let values=[...D[x]];
  if(config.values==='lcv'){const score=v=>neighbors(P,x).filter(y=>!(y in A)).reduce((s,y)=>s+legal(y,D,A).filter(w=>!P.test(x,v,y,w)).length,0);values.sort((a,b)=>score(a)-score(b)||COLORS.indexOf(a)-COLORS.indexOf(b));}
  emit(`Select ${x}; try values ${values.join(', ')||'∅'}.`,D,A);
  for(const v of values){counts.attempts++;if(!legal(x,D,A).includes(v)){emit(`Reject ${x}=${v}: conflicts with an assigned neighbour.`,D,A);continue;}
   let child=clone(D);child[x]=[v];const next={...A,[x]:v};emit(`Assign ${x}=${v}.`,child,next);let ok=true;
   if(config.inference==='fc'){for(const y of neighbors(P,x))if(!(y in next))child[y]=child[y].filter(w=>P.test(x,v,y,w));ok=AU.every(y=>child[y].length);emit(`Forward checking after ${x}=${v}: ${ok?'domains survive':'an empty domain rejects this branch'}.`,child,next);}
   if(config.inference==='mac'){const result=ac3(P,child);child=result.D;ok=result.ok;emit(`AC-3 after ${x}=${v}: ${ok?'arc-consistent fixed point':'empty domain; reject branch'}.`,child,next);}
   if(ok&&visit(child,next))return true;
   counts.backtracks++;emit(`Undo ${x}=${v}; restore the parent assignment and domains.`,D,A);
  }return false;
 }
 let start=base;emit('Initial domains; no variables assigned.',start,{});if(config.inference==='mac'){const a=ac3(P,start);start=a.D;emit('Root AC-3: '+(a.ok?'nonempty fixed point.':'empty domain.'),start,{});if(!a.ok){emit('UNSAT: root propagation proves failure.',start,{},'UNSAT');return {events,solution,counts};}}
 if(!visit(start,{}))emit('UNSAT: all branches have been exhausted.',start,{},'UNSAT');return {events,solution,counts};}
let bt,btPos=0;function btDraw(){const e=bt.events[btPos];renderDomains('bt-domains',AU,e.D,e.A);byId('bt-event').textContent=e.message;byId('bt-counts').textContent=`Event ${btPos+1}/${bt.events.length} · Value attempts ${e.counts.attempts} · Branches undone ${e.counts.backtracks}`;byId('bt-assignment').textContent='Assignment: '+(AU.filter(x=>x in e.A).map(x=>x+'='+e.A[x]).join(', ')||'empty');byId('bt-back').disabled=btPos===0;byId('bt-step').disabled=byId('bt-run').disabled=btPos===bt.events.length-1;}
function btReset(){bt=backtrackTrace({colors:Number(byId('bt-colors').value),order:byId('bt-order').value,inference:byId('bt-inference').value,values:byId('bt-values').value});btPos=0;btDraw();}
byId('bt-back').onclick=()=>{btPos=Math.max(0,btPos-1);btDraw();};byId('bt-step').onclick=()=>{btPos=Math.min(bt.events.length-1,btPos+1);btDraw();};byId('bt-run').onclick=()=>{btPos=bt.events.length-1;btDraw();};byId('bt-reset').onclick=btReset;['bt-colors','bt-order','bt-inference','bt-values'].forEach(id=>byId(id).onchange=btReset);btReset();
function acProblem(which){if(which==='chain')return {P:{vars:['X','Y','Z'],edges:[['X','Y'],['Y','Z']],test:(a,x,b,y)=>a<b?x<y:x>y},D:initialDomains(['X','Y','Z'],[1,2,3])};return {P:{vars:['A','B','C'],edges:[['A','B'],['B','C'],['C','A']],test:(a,x,b,y)=>x!==y},D:initialDomains(['A','B','C'],['R','G'])};}
let acState,acPos=0;function acDraw(){const e=acState.result.events[acPos];renderDomains('ac-domains',acState.P.vars,e.D);byId('ac-event').textContent=e.message;byId('ac-queue').innerHTML=e.queue.length?e.queue.map(([a,b])=>`<span>${a} → ${b}</span>`).join(''):'<span>Empty</span>';byId('ac-solutions').textContent=acState.solutions.length+' solution'+(acState.solutions.length===1?'':'s');byId('ac-back').disabled=acPos===0;byId('ac-step').disabled=byId('ac-run').disabled=acPos===acState.result.events.length-1;}
function acReset(){const {P,D}=acProblem(byId('ac-case').value);acState={P,D,result:ac3(P,D),solutions:enumerate(P,D)};acPos=0;acDraw();}byId('ac-case').onchange=acReset;byId('ac-reset').onclick=acReset;byId('ac-step').onclick=()=>{acPos=Math.min(acState.result.events.length-1,acPos+1);acDraw();};byId('ac-back').onclick=()=>{acPos=Math.max(0,acPos-1);acDraw();};byId('ac-run').onclick=()=>{acPos=acState.result.events.length-1;acDraw();};acReset();
function allDifferent(which,mode){const P={vars:['A','B','C'],edges:[['A','B'],['A','C'],['B','C']],test:(a,x,b,y)=>x!==y},base={A:[1,2],B:[1,2],C:which==='hall'?[1,2,3]:[1,2]},tuples=enumerate(P,base);let D=clone(base);if(mode==='pair')D=ac3(P,base).D;if(mode==='global')D=Object.fromEntries(P.vars.map(x=>[x,base[x].filter(v=>tuples.some(t=>t[x]===v))]));return {D,base,tuples,mode};}
let allState;function allDraw(mode='initial'){allState=allDifferent(byId('all-case').value,mode);renderDomains('all-domains',['A','B','C'],allState.D);byId('all-tuples').textContent=allState.tuples.length?allState.tuples.map(t=>'('+[t.A,t.B,t.C].join(', ')+')').join(' · '):'0 valid triples';byId('all-status').textContent=mode==='initial'?'Original domains. Choose a propagation method.':mode==='pair'?'Pairwise AC: no values removed. This does not prove satisfiability.':allState.tuples.length?'Global GAC: C=1 and C=2 have no full-tuple support. Keep C={3}.':'Global GAC: no valid triple exists. FAILURE.';}byId('all-case').onchange=()=>allDraw();byId('all-reset').onclick=()=>allDraw();byId('all-pair').onclick=()=>allDraw('pair');byId('all-global').onclick=()=>allDraw('global');allDraw();
const QUEEN_SOLUTION=[1,7,5,8,2,4,6,3];let qRows=[],qSteps=0,qRng,qMessage='';
function seeded(seed){let a=seed>>>0;return ()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296;};}
function queenPairs(q){const pairs=[];for(let i=0;i<q.length;i++)for(let j=i+1;j<q.length;j++)if(q[i]===q[j]||Math.abs(q[i]-q[j])===j-i)pairs.push([i,j]);return pairs;}
function queenStep(){const pairs=queenPairs(qRows);if(!pairs.length||qSteps>=200)return;const columns=[...new Set(pairs.flat())].sort((a,b)=>a-b),col=columns[Math.floor(qRng()*columns.length)];const scores=Array.from({length:8},(_,i)=>qRows.reduce((s,r,j)=>s+(j!==col&&(r===i+1||Math.abs(r-i-1)===Math.abs(j-col))?1:0),0)),min=Math.min(...scores),best=scores.flatMap((s,i)=>s===min?[i+1]:[]),row=best[Math.floor(qRng()*best.length)],old=qRows[col];qRows[col]=row;qSteps++;qMessage=`Column ${col+1}: row ${old} → ${row}; ${min} conflicts involve this queen.`;}
function queenDraw(){const pairs=queenPairs(qRows),conflicted=new Set(pairs.flat());byId('queen-board').innerHTML=Array.from({length:64},(_,i)=>{const r=Math.floor(i/8)+1,c=i%8,queen=qRows[c]===r;return `<button class="${(r-1+c)%2?'shade ':''}${queen?'queen ':''}${queen&&conflicted.has(c)?'conflicted':''}" data-row="${r}" data-col="${c}" aria-label="Row ${r}, column ${c+1}${queen?', queen'+(conflicted.has(c)?' in conflict':''):''}">${queen?'Q':''}</button>`;}).join('');byId('queen-conflicts').textContent=pairs.length;byId('queen-status').textContent=!pairs.length?`SOLUTION · ${qSteps} repair attempts.`:qSteps>=200?'BUDGET_EXHAUSTED · 200 attempts. This is not a proof of UNSAT.':`Attempt ${qSteps}/200. ${qMessage||'Complete assignment; conflicts remain.'}`;byId('queen-vector').textContent='Rows: ['+qRows.join(', ')+']';byId('queen-step').disabled=byId('queen-run').disabled=!pairs.length||qSteps>=200;}
function queenReset(){const seed=Math.max(1,Math.min(999999,Math.floor(Number(byId('queen-seed').value)||1)));byId('queen-seed').value=seed;qRng=seeded(seed);qRows=Array.from({length:8},()=>1+Math.floor(qRng()*8));qSteps=0;qMessage='Seed '+seed+' initialized the board.';queenDraw();}
byId('queen-board').onclick=e=>{const b=e.target.closest('button[data-row]');if(!b)return;qRows[Number(b.dataset.col)]=Number(b.dataset.row);qSteps=0;qMessage='Manual edit; repair budget reset.';queenDraw();};byId('queen-step').onclick=()=>{queenStep();queenDraw();};byId('queen-run').onclick=()=>{while(qSteps<200&&queenPairs(qRows).length)queenStep();queenDraw();};byId('queen-reset').onclick=queenReset;byId('queen-solution').onclick=()=>{qRows=[...QUEEN_SOLUTION];qSteps=0;qMessage='';queenDraw();};queenReset();
window.presentation={go,slides,ac3,enumerate,auProblem,initialDomains,backtrackTrace,allDifferent,queenPairs,seeded,getMap:mapDraw,getBT:()=>({trace:clone(bt),position:btPos}),getAC:()=>({D:clone(acState.result.events[acPos].D),position:acPos,result:clone(acState.result)}),getAll:()=>clone(allState),getQueens:()=>({rows:[...qRows],steps:qSteps,pairs:queenPairs(qRows)}),reset:()=>{mapA={};byId('map-var').value='WA';byId('map-value').value='R';mapDraw();byId('bt-colors').value='3';byId('bt-order').value='mrv';byId('bt-inference').value='fc';byId('bt-values').value='fixed';btReset();byId('ac-case').value='chain';acReset();byId('all-case').value='hall';allDraw();byId('queen-seed').value='1';queenReset();}};

window.addEventListener("beforeprint",()=>slides.forEach(s=>s.setAttribute("aria-hidden","false")));
window.addEventListener("afterprint",()=>go(current,false));
