const U6=(()=>{
 const $=id=>document.getElementById(id),arrows=['↑','→','↓','←'],names=['Up','Right','Down','Left'];
 const fmt=(x,n=3)=>Math.abs(x)<0.5*10**(-n)?(0).toFixed(n):x.toFixed(n).replace('-','−');
 const bests=v=>{const m=Math.max(...v);return v.map((x,i)=>Math.abs(x-m)<1e-10?i:-1).filter(i=>i>=0);};
 function rng(seed){let a=seed>>>0;return ()=>{a=(a+0x6D2B79F5)>>>0;let t=a;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return ((t^(t>>>14))>>>0)/4294967296;};}
 function seedValue(id){let n=Number($(id).value);n=Number.isFinite(n)?Math.max(1,Math.min(9999,Math.round(n))):1;$(id).value=n;return n;}
 const terminal=s=>s===3||s===7,states=[0,1,2,4,6,8,9,10,11],dirs=[[-1,0],[0,1],[1,0],[0,-1]];
 function move(s,a){const [dr,dc]=dirs[a],r=Math.floor(s/4)+dr,c=s%4+dc,t=4*r+c;return r<0||r>=3||c<0||c>=4||t===5?s:t;}
 function transitions(s,a,p=.8,cost=-.04){if(terminal(s))return [{p:1,s,r:0}];return [[p,a],[(1-p)/2,(a+1)%4],[(1-p)/2,(a+3)%4]].map(([prob,d])=>{const t=move(s,d);return {p:prob,s:t,r:t===3?1:t===7?-1:cost};}).filter(x=>x.p>0);}
 function actionValues(v,s,p=.8,g=.9){return [0,1,2,3].map(a=>transitions(s,a,p).reduce((sum,t)=>sum+t.p*(t.r+g*v[t.s]),0));}
 function backup(v,p=.8,g=.9){const w=Array(12).fill(0);states.forEach(s=>w[s]=Math.max(...actionValues(v,s,p,g)));return w;}
 function residual(v,p,g){const w=backup(v,p,g);return Math.max(...v.map((x,s)=>Math.abs(x-w[s])));}
 function sample(s,a,p,random){const ts=transitions(s,a,p),u=random();let cum=0;for(const t of ts){cum+=t.p;if(u<cum)return t;}return ts.at(-1);}
 function gridHTML(v,policy){return Array.from({length:12},(_,s)=>{const cls=s===5?'wall':terminal(s)?'terminal':s===8?'start':'';const coord=`(${Math.floor(s/4)+1},${s%4+1})`;return `<div class="cell ${cls}" aria-label="${s===5?'Wall':terminal(s)?coord+' terminal entry reward '+(s===3?1:-1):coord+', value '+fmt(v[s])+'; greedy actions '+policy[s].map(a=>names[a]).join(', ')}"><small>${s===5?'':coord+(s===8?' Start':'')}</small><b>${s===5?'Wall':terminal(s)?(s===3?'+1':'−1'):fmt(v[s])}</b><em>${s===5?'':terminal(s)?'terminal · V=0':policy[s].map(a=>arrows[a]).join('')}</em></div>`;}).join('');}
 function lineChart(data,{label,min=-1,max=1,reference=null}={}){
  const w=550,h=160,left=55,right=16,top=15,bottom=34,iw=w-left-right,ih=h-top-bottom,n=data.length;
  const y=v=>top+(max-v)/(max-min)*ih,x=i=>left+(n>1?i/(n-1):0)*iw;
  const stride=Math.max(1,Math.ceil(n/110)),indices=[];for(let i=0;i<n;i+=stride)indices.push(i);if(n&&indices.at(-1)!==n-1)indices.push(n-1);
  const pts=indices.map(i=>`${x(i).toFixed(2)},${y(data[i]).toFixed(2)}`).join(' ');
  return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${label}. ${n?`${n} observations. Latest ${fmt(data.at(-1))}.`:'No observations yet.'}"><path d="M${left} ${top}V${h-bottom}H${w-right}" class="axis"/>${[min,(max+min)/2,max].map(v=>`<text x="${left-9}" y="${y(v)+5}" text-anchor="end">${fmt(v,1)}</text>`).join('')}${reference===null?'':`<line class="reference" x1="${left}" x2="${w-right}" y1="${y(reference)}" y2="${y(reference)}"/><text x="${w-right}" y="${y(reference)-6}" text-anchor="end">best mean ${reference}</text>`}${n>1?`<polyline class="series" points="${pts}"/>`:n?`<circle class="point" cx="${x(0)}" cy="${y(data[0])}" r="4"/>`:''}<text x="${left}" y="${h-10}">${n?'1':'0'}</text><text x="${w-right}" y="${h-10}" text-anchor="end">${n}</text><text x="${(left+w-right)/2}" y="${h-10}" text-anchor="middle">${label}</text></svg>`;
 }
 // Laboratory 1: finite-trajectory discounted returns.
 let returnGamma=.9;
 const returnValue=(rewards,g)=>rewards.reduce((s,r,i)=>s+r*g**i,0);
 function renderReturn(){const g=returnGamma,patient=returnValue([-1,-1,5],g),tie=Math.abs(patient-1)<1e-10;
  $('return-gamma-label').textContent=fmt(g,6);$('return-bars').innerHTML=[['Quick',1],['Patient',patient]].map(([label,v])=>`<div class="return-row"><span>${label}</span><b>${fmt(v)}</b><div class="return-track"><i style="width:${Math.abs(v)/3*100}%;background:${v<0?'#9da1ac':'#ff5277'}"></i></div></div>`).join('');
  $('return-terms').innerHTML=`<h3>Patient: weighted rewards</h3><div class="reward-terms"><span>−1<b>−1.000</b></span><span>−γ<b>${fmt(-g)}</b></span><span>5γ²<b>${fmt(5*g*g)}</b></span></div>`;
  $('return-status').textContent=tie?'Tie: both returns equal 1. The exact threshold is (1+√41)/10 ≈ 0.740312.':`${patient>1?'Patient':'Quick'} has the larger return. Patient − Quick = ${fmt(patient-1)}.`;
 }
 $('return-gamma').oninput=()=>{returnGamma=Number($('return-gamma').value);renderReturn();};
 function setReturn(g){returnGamma=g;$('return-gamma').value=g;renderReturn();}
 $('return-short').onclick=()=>setReturn(0);$('return-long').onclick=()=>setReturn(.9);$('return-tie').onclick=()=>setReturn((1+Math.sqrt(41))/10);
 // Laboratory 2: synchronous exact model backups.
 let vi={};
 function renderVI(){const {v,p,g,k,delta}=vi,pol=Array.from({length:12},(_,s)=>states.includes(s)?bests(actionValues(v,s,p,g)):[]),res=residual(v,p,g);$('vi-grid').innerHTML=gridHTML(v,pol);$('vi-k').textContent=k;$('vi-delta').textContent=k?delta.toExponential(2):'—';$('vi-start').textContent=fmt(v[8],5);$('vi-residual').textContent=res.toExponential(2);$('vi-gamma-label').textContent=fmt(g,2);$('vi-p-label').textContent=fmt(p,1);$('vi-status').textContent=k===0?'Zero initialization. Predict which cells change in the first sweep.':res<1e-8?`Residual below 10⁻⁸. Value error is bounded by residual/(1−γ) = ${(res/(1-g)).toExponential(2)}.`:`Sweep ${k}: every new value used the previous vector. Sideways probabilities are ${fmt((1-p)/2,2)} each.`;}
 function resetVI(){vi={v:Array(12).fill(0),k:0,delta:0,p:Number($('vi-p').value),g:Number($('vi-gamma').value)};renderVI();}
 function viSteps(n){for(let i=0;i<n;i++){const w=backup(vi.v,vi.p,vi.g);vi.delta=Math.max(...w.map((x,s)=>Math.abs(x-vi.v[s])));vi.v=w;vi.k++;}renderVI();}
 function solveVI(){let n=0;while(residual(vi.v,vi.p,vi.g)>=1e-8&&n<2000){const w=backup(vi.v,vi.p,vi.g);vi.delta=Math.max(...w.map((x,s)=>Math.abs(x-vi.v[s])));vi.v=w;vi.k++;n++;}renderVI();}
 $('vi-step').onclick=()=>viSteps(1);$('vi-ten').onclick=()=>viSteps(10);$('vi-solve').onclick=solveVI;$('vi-reset').onclick=resetVI;['vi-p','vi-gamma'].forEach(id=>$(id).oninput=resetVI);
 // Laboratory 3: terminal-safe update arithmetic.
 function updateTargets({alpha=.2,gamma=.9,reward=-.04,terminated=false,selected=1}={}){const old=.5,vNext=2,qNext=[4,1,-2,0];return [['TD(0)',vNext],['Q-learning',Math.max(...qNext)],['SARSA',qNext[selected]]].map(([name,next])=>{const target=reward+(terminated?0:gamma*next),error=target-old;return {name,target,error,value:old+alpha*error};});}
 function renderUpdate(){const kind=$('update-case').value,alpha=Number($('update-alpha').value),gamma=Number($('update-gamma').value),selected=Number($('update-action').value),terminated=kind==='terminal',r=terminated?1:-.04,results=updateTargets({alpha,gamma,selected,terminated,reward:r});$('update-alpha-label').textContent=fmt(alpha,2);$('update-gamma-label').textContent=fmt(gamma,2);$('update-action').disabled=terminated;$('update-table').innerHTML='<table><thead><tr><th>Method</th><th>Target</th><th>New estimate</th></tr></thead><tbody>'+results.map(x=>`<tr><td>${x.name}</td><td>${fmt(x.target)}</td><td>${fmt(x.value)}</td></tr>`).join('')+'</tbody></table>';$('update-status').textContent=terminated?'True terminal: all continuation terms are zero. The target is the final reward +1.':kind==='truncated'?'External cutoff: continuation stays in the target. Use the final next state before resetting.':`SARSA uses ${names[selected]}. Q-learning uses the maximum next value 4. TD uses V(s′)=2.`;return results;}
 function resetUpdate(){$('update-case').value='ordinary';$('update-alpha').value='.2';$('update-gamma').value='.9';$('update-action').value='1';renderUpdate();}
 ['update-case','update-alpha','update-gamma','update-action'].forEach(id=>$(id).oninput=renderUpdate);$('update-reset').onclick=resetUpdate;
 // Laboratory 4: Bernoulli bandit, sample means, explicit tie rule.
 const means=[.2,.5,.8];let bandit={};
 function resetBandit(){const seed=seedValue('bandit-seed');bandit={seed,random:rng(seed),epsilon:Number($('bandit-epsilon').value),q:[0,0,0],counts:[0,0,0],n:0,total:0,regret:0,curve:[],last:null};renderBandit();}
 function banditPulls(n){n=Math.min(n,10000-bandit.n);for(let t=0;t<n;t++){const b=bandit,a=b.random()<b.epsilon?Math.floor(b.random()*3):bests(b.q)[0],reward=b.random()<means[a]?1:0;b.n++;b.counts[a]++;b.q[a]+=(reward-b.q[a])/b.counts[a];b.total+=reward;b.regret+=.8-means[a];b.curve.push(b.total/b.n);b.last={a,reward};}renderBandit();}
 function renderBandit(){const b=bandit;$('bandit-table').innerHTML='<table><thead><tr><th>Action</th><th>True p</th><th>Q̂</th><th>Pulls</th></tr></thead><tbody>'+means.map((p,a)=>`<tr><td>${'ABC'[a]}</td><td>${fmt(p,1)}</td><td>${fmt(b.q[a])}</td><td>${b.counts[a]}</td></tr>`).join('')+'</tbody></table>';$('bandit-chart').innerHTML=lineChart(b.curve,{label:'Mean reward / pulls',min:0,max:1,reference:.8});$('bandit-n').textContent=b.n.toLocaleString('en');$('bandit-mean').textContent=b.n?fmt(b.total/b.n):'—';$('bandit-best').textContent=b.n?fmt(100*b.counts[2]/b.n,1)+'%':'—';$('bandit-regret').textContent=fmt(b.regret,1);$('bandit-status').textContent=b.last?`Last: action ${'ABC'[b.last.a]}, reward ${b.last.reward}. Seed ${b.seed}. ${b.n>=10000?'10,000-pull limit reached. Reset to restart.':'Change ε or seed to start a new run.'}`:'All estimates start at 0. Greedy ties favour A, then B, then C. Predict the effect of ε=0.';['bandit-one','bandit-hundred','bandit-thousand'].forEach(id=>$(id).disabled=b.n>=10000);}
 $('bandit-one').onclick=()=>banditPulls(1);$('bandit-hundred').onclick=()=>banditPulls(100);$('bandit-thousand').onclick=()=>banditPulls(1000);$('bandit-reset').onclick=resetBandit;$('bandit-epsilon').onchange=resetBandit;$('bandit-seed').onchange=resetBandit;
 // Laboratory 5: tabular control from sampled transitions.
 function epsilonAction(q,epsilon,random,randomTies=true){if(random()<epsilon)return Math.floor(random()*q.length);const bs=bests(q);return randomTies&&bs.length>1?bs[Math.floor(random()*bs.length)]:bs[0];}
 function createTrainer({seed=17,p=1,epsilon=.3,alpha=.3,method='q'}={}){return {seed,p,epsilon,alpha,method,gamma:.9,random:rng(seed),q:Array.from({length:12},()=>[0,0,0,0]),n:0,steps:0,returns:[],last:null,evaluation:null};}
 function trainEpisodes(t,n){n=Math.min(n,10000-t.n);for(let ep=0;ep<n;ep++){let s=8,a=epsilonAction(t.q[s],t.epsilon,t.random),G=0,factor=1,last=null;for(let k=0;k<100;k++){const out=sample(s,a,t.p,t.random),done=terminal(out.s),nextAction=done?null:epsilonAction(t.q[out.s],t.epsilon,t.random),cont=done?0:t.method==='q'?Math.max(...t.q[out.s]):t.q[out.s][nextAction],target=out.r+t.gamma*cont;t.q[s][a]+=t.alpha*(target-t.q[s][a]);t.steps++;G+=factor*out.r;factor*=t.gamma;last={state:out.s,steps:k+1,kind:done?(out.s===3?'goal':'failure'):k===99?'cap':'ongoing'};if(done)break;s=out.s;a=nextAction;}t.n++;t.returns.push(G);t.last={...last,G};}t.evaluation=null;return t;}
 function evaluateTrainer(t,n=100){const random=rng((t.seed+1000003)>>>0),report={n,goals:0,failures:0,caps:0,mean:0,returns:[]};for(let ep=0;ep<n;ep++){let s=8,G=0,factor=1,ended=false;for(let k=0;k<100;k++){const a=bests(t.q[s])[0],out=sample(s,a,t.p,random);G+=factor*out.r;factor*=t.gamma;s=out.s;if(terminal(s)){report[s===3?'goals':'failures']++;ended=true;break;}}if(!ended)report.caps++;report.returns.push(G);report.mean+=G/n;}return report;}
 let trainer;
 function resetTrainer(){trainer=createTrainer({seed:seedValue('train-seed'),p:Number($('train-p').value),epsilon:Number($('train-epsilon').value),alpha:Number($('train-alpha').value),method:$('train-method').value});renderTrainer();}
 function renderTrainer(){const t=trainer,v=t.q.map(row=>Math.max(...row)),pol=t.q.map(bests);$('train-grid').innerHTML=gridHTML(v,pol);let sum=0;const curve=t.returns.map((v,i)=>{sum+=v;if(i>=20)sum-=t.returns[i-20];return sum/Math.min(i+1,20);});$('train-chart').innerHTML=lineChart(curve,{label:'Mean return / episodes',min:-1,max:.6});$('train-n').textContent=t.n.toLocaleString('en');$('train-steps').textContent=t.steps.toLocaleString('en');$('train-status').textContent=t.last?`Latest: ${t.last.kind}, ${t.last.steps} steps, return ${fmt(t.last.G)}. ${t.n>=10000?'10,000-episode limit reached.':'γ=0.9. Rollouts stop after at most 100 steps.'}`:'Zero Q-table. Train, then evaluate the frozen greedy policy. Changing a setting starts over.';const e=t.evaluation;$('train-eval-result').textContent=e?`Frozen evaluation: ${e.goals}/100 goals, ${e.failures} failures, ${e.caps} caps. Mean return ${fmt(e.mean,5)}. ε=0; no updates.`:'Evaluation has not run for this Q-table.';['train-one','train-hundred','train-thousand'].forEach(id=>$(id).disabled=t.n>=10000);}
 function trainBatch(n){trainEpisodes(trainer,n);renderTrainer();}
 function evaluate(){trainer.evaluation=evaluateTrainer(trainer,100);renderTrainer();}
 $('train-one').onclick=()=>trainBatch(1);$('train-hundred').onclick=()=>trainBatch(100);$('train-thousand').onclick=()=>trainBatch(1000);$('train-eval').onclick=evaluate;$('train-reset').onclick=resetTrainer;['train-method','train-p','train-epsilon','train-alpha','train-seed'].forEach(id=>$(id).onchange=resetTrainer);
 function reset(){setReturn(.9);$('vi-gamma').value='0.9';$('vi-p').value='0.8';resetVI();resetUpdate();$('bandit-epsilon').value='0.1';$('bandit-seed').value='1';resetBandit();$('train-method').value='q';$('train-p').value='1';$('train-epsilon').value='0.3';$('train-alpha').value='0.3';$('train-seed').value='17';resetTrainer();}
 reset();
 return {reset,rng,returnValue,transitions,move,backup,residual,actionValues,updateTargets,createTrainer,trainEpisodes,evaluateTrainer,epsilonAction,bests,getVI:()=>vi,getBandit:()=>bandit,getTrainer:()=>trainer,getReturn:()=>returnGamma,solveVI,viSteps,banditPulls,trainBatch,evaluate};
})();
window.presentation={go,slides,...U6};
window.addEventListener('beforeprint',()=>slides.forEach(s=>s.setAttribute('aria-hidden','false')));
window.addEventListener('afterprint',()=>go(current,false));
